### ISSUE TITLE
Suggesting new features

### ISSUE THREAD

**Issue by ghost** [MikeMoolenaar/Migaku-Japanese-Addon-Updated#6]
Hello, I would like to suggest some features that I believe would be great additions to the addon.

**1# ALLOW THE ADDON TO WORK WITH VARIABLES.**

When working with the addon using fields, you cannot modify the content of the field, or the addon will stop functioning. I think this When using the addon with fields, currently, you cannot modify the content of the field, or the addon will cease to function. I believe this limitation restricts the potential functionality of the addon (I'm new to this, so it might be my lack of experience), and it can be inconvenient.

For example, as the addon currently functions, if you have 20 words in a note and you want to navigate through them using buttons, you would need 20 fields instead of being able to manage it from just one.

I propose allowing the addon to work with variables. This could involve changing "Active Fields" to "Active Notes" and, in the preview (by adding options to the right-click menu like "Colored Kanji," etc.), enabling the selection of the variable you want and the addition of the necessary code for the addon to function automatically.

**2# IMPLEMENT THE SEARCH IN COLLECTION SHORTCUT FROM MIGAKU DICTIONARY ADDON**

In Migaku Dictionary, you could use Ctrl+S to search in the dictionary and Ctrl+Shift+S to search in the collection. I suggest substituting the dictionary search since Yomi-chan already covers its function perfectly. Instead, we could use Ctrl+S to search in the same deck as the card whose text you have selected.

**3# HIGHLIGHTING TEXT**

Essentially, an automatic F3 function when searching, with the search term highlighted, and the ability to navigate through all the highlighted words.

I would love to hear your thoughts on these suggestions.

**Comment by MikeMoolenaar** [comment]
Hey here are my thoughts:
1#: it's a very niche feature, though I don't fully understand what you are trying to achieve? Maybe there is some way to do this in your template with Javascript.
2# and 3#: I believe these are great but it's outside the scope of this addon I think. I haven't tried any of these addons but try these:
- https://ankiweb.net/shared/info/225180905 Highlight in search and jump between results
- https://ankiweb.net/shared/info/227080119 search in the review screen

**Comment by TheGuyWithAProblem** [comment]
I'm new to coding, so it's possible that there's a solution I'm not aware of. What I'm trying to achieve is to have multiple words within a field using the Migaku syntax, but display only one word at a time. Ideally, I'd like to be able to switch which word is displayed using buttons or a similar mechanism.

Since coding isn't my strong suit, I'm unsure if I can create my own add-on with these features, but I'm willing to give it a try. In the meantime, I'll make use of the add-ons you recommended!

One more thing I'd like to suggest is a change in the syntax of the words. Recently, I came across this [addon](https://github.com/Ben-Kerman/anki-jrp). After reading through its syntax section, I realized that there might be room for improvements in the syntax. It's something you might want to consider.

**Comment by MikeMoolenaar** [comment]
> Ideally, I'd like to be able to switch which word is displayed using buttons or a similar mechanism

Yeah should be possible in the card template, keep learning about Javascript and HTML.

> One more thing I'd like to suggest is a change in the syntax of the words

That syntax is better, but I can't just change the syntax because my old cards will break. That addon is nice and seems like a great option if you don't have existing cards modified using the Migaku syntax. If I would start from scratch I would probably use that addon lol.

Anyway, have fun coding, i'll just close this issue as a won't fix.
